### ISSUE TITLE
Import initial file

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-explorer#1]
#### Overview
Let's start by taking the [viewModelBuilders/common/utils.ts](https://github.com/clevercanary/data-browser/blob/main/explorer/app/viewModelBuilders/common/utils.ts) file and importing it into this repository, I believe under `src/viewModelBuilders/common`, deleting it from the application,  and then importing this back into the application via npm.

This will get us through some mechanics, like working simultaneously on the application and this dependency and working with typescript.

See this article on how to develop the app and the dependency simultaneously
https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557

For inspiration look at:
https://github.com/mui/material-ui/tree/master/packages/mui-base/src/utils and
https://github.com/TanStack/table/tree/main/packages

Also for a 101 on creating a Typescript package from scratch see:
https://spin.atomicobject.com/2022/06/21/npm-package-typescript/

#### Tasks
- [ ] Determine/specify module type likely "ES modules"
- [ ] create tsconfig.json (does this need to be any different than the one we use for the project?) See: [this example](https://github.com/TanStack/table/blob/main/packages/match-sorter-utils/tsconfig.json) from react table for inspiration. 
- [ ] do we need to export any type information?
